name: StelyChairs
version: 1.3
description: Let players sit on stairs and slabs.
author: spoothie
main: net.spoothie.chairs.Chairs
api-version: 1.13
commands:
    chairs:
        description: Reloads the Chairs configuration file.
        usage: /chairs reload