name: StelyChairs
version: 1.4
description: Let players sit on stairs and slabs.
author: spoothie,LightMute
main: net.spoothie.chairs.Chairs
api-version: 1.14
commands:
    chairs:
        description: Reloads the Chairs configuration file.
        usage: /chairs reload